services:
  redis:
    container_name: nasa-redis
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - nasa-network
  mongo:
    image: mongo:latest
    container_name: nasa-mongo-db
    ports:
      - "27017:27017"
    networks:
      - nasa-network
    volumes:
      - mongo-data:/data/db
  server:
    build: ./server
    # ports:
    #   - "8000:3000"
    networks:
      - nasa-network
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - MONGO_URL=mongodb://mongo:27017/nasa
      - REDIS_PORT=6379
      - REDIS_HOST=nasa-redis
    depends_on:
      - mongo
      - redis
  client:
    build:
      context: ./client
      # target: 
      args:
        REACT_APP_API_BASE: https://${APP_DOMAIN}/api/v1
    # ports:
    #   - "5000:80"
    env_file: ./.env
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - nasa-network
    depends_on:
      - server
  nginx-server:
    build:
      context: ./nginx
      args:
        APP_DOMAIN: ${APP_DOMAIN}
        NODE_ENV: development
    env_file: ./.env
    ports:
      - 80:80
      - 443:443
    networks:
      - nasa-network
    volumes:
      - ./nginx/default.conf.template.dev:/etc/nginx/templates/default.conf.template
    depends_on:
      - server
      - client
networks:
  nasa-network:
    driver: bridge
volumes:
  mongo-data:
  redis-data:
