services:
  server:
    build: ./server
    # ports:
    #   - "8000:3000"
    networks:
      - nasa-app
    # environment:
    #   - TEST_ENV=xxxxxxxxxxxxxx
  client:
    build:
      context: ./client
      # target: 
      args:
        REACT_APP_API_BASE: https://${APP_DOMAIN}/api/v1
    # ports:
    #   - "5000:80"
    env_file: ./.env
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - nasa-app
    depends_on:
      - server
  nginx-server:
    build:
      context: ./nginx
      args:
        APP_DOMAIN: ${APP_DOMAIN}
        NODE_ENV: development
    env_file: ./.env
    ports:
      - 80:80
      - 443:443
    networks:
      - nasa-app
    volumes:
      - ./nginx/default.conf.template.dev:/etc/nginx/templates/default.conf.template
    depends_on:
      - server
      - client
networks:
  nasa-app:
    driver: bridge