name: NASA Project CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: 
      - ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Get in the NASA Project directory
        run: cd NASA
      - name: Install client packages
        run: |
          cd client
          npm install
          cd ..
      - name: Build
        run: npm run build --prefix client
      - name: Test
        run: npm test
      - name: Deploy
        run: |
          echo "Deploying to production..."
          echo "Deployed!"