name: NASA Project CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: 
      - ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install client packages and build
        working-directory: ./NASA/client
        run: |
          npm install
          npm run build
      - name: Test server
        working-directory: ./NASA
        run: npm run test
      - name: Deploy
        run: |
          echo "Deploying to production..."
          echo "Deployed!"